version: '3.3'

volumes:
  influx_conf:
  influx_data:

services:
  influx:
    image: influxdb
    volumes:
      - influx_conf:/etc/influxdb2
      - influx_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_ADMIN}
    ports:
      - '127.0.0.1:${INFLUX_PORT}:8086'
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8086 || exit 1